# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'promobitIOS' do
  pod 'PKHUD', '~> 5.0'
  pod 'Alamofire', '~> 5.2'
  pod 'Kingfisher', '~> 5.0'
  pod 'SideMenu', '~> 5.0'
  pod 'Firebase/Analytics'
  use_frameworks!

  # Pods for promobitIOS

  target 'promobitIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'promobitIOSUITests' do
    # Pods for testing
  end

end
